### ISSUE TITLE
snake头部坐标移动 不对吧 

### ISSUE THREAD

**Issue by coderlongren** [i1mT/C-Snake#2]
//找到头并将头的坐标保留用于下一个补上来
	x = snake[head][1];
	y = snake[head][2];
	switch (direct){
		case 1://向上
			snake[head][2]--;//横坐标不变，纵坐标-1
			break;
		case 2://向下
			snake[head][2]++;//横坐标不变 ，纵坐标+1
			break;
		case 3://向左
			snake[head][1]--;//纵坐标不变，横坐标-1
			break;
		case 4://向右
			snake[head][1]++;//纵坐标不变，横坐标+1
			break;
	}

**Comment by i1mT** [comment]
哪里有问题呢？

**Comment by coderlongren** [comment]
is my error of env
